[package]
name = "igloo-api"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
igloo-core.workspace = true
jiff.workspace = true
serde.workspace = true
utoipa.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
