//! The server <-> worker gRPC contract (`igloo.worker.v1`), generated from `proto/`, plus
//! conversions to and from `igloo-core` types.
//!
//! Data only: generated types and conversions. Field numbers are never reused; removed fields
//! are `reserved`.

mod convert;

pub use convert::ProtocolError;

/// Generated types and the `WorkerGatewayService` client and server.
#[allow(
    missing_docs,
    unreachable_pub,
    clippy::pedantic,
    clippy::default_trait_access,
    reason = "generated by tonic-prost-build"
)]
pub mod v1 {
    tonic::include_proto!("igloo.worker.v1");
}
