/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSystemRouteImport } from './routes/_app/system'
import { Route as AppChangesIndexRouteImport } from './routes/_app/changes.index'
import { Route as AppChangesIdRouteImport } from './routes/_app/changes.$id'
import { Route as AppJobsIdRouteImport } from './routes/_app/jobs.$id'
import { Route as AppRunsIdRouteImport } from './routes/_app/runs.$id'
import { Route as AppTasksIndexRouteImport } from './routes/_app/tasks.index'
import { Route as AppTasksIdRouteImport } from './routes/_app/tasks.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRoute = AppSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppRoute,
} as any)
const AppChangesIndexRoute = AppChangesIndexRouteImport.update({
  id: '/changes/',
  path: '/changes/',
  getParentRoute: () => AppRoute,
} as any)
const AppChangesIdRoute = AppChangesIdRouteImport.update({
  id: '/changes/$id',
  path: '/changes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIdRoute = AppJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsIdRoute = AppRunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIdRoute = AppTasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/signin': typeof SigninRoute
  '/settings': typeof AppSettingsRoute
  '/system': typeof AppSystemRoute
  '/changes/$id': typeof AppChangesIdRoute
  '/jobs/$id': typeof AppJobsIdRoute
  '/runs/$id': typeof AppRunsIdRoute
  '/tasks/$id': typeof AppTasksIdRoute
  '/changes/': typeof AppChangesIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/settings': typeof AppSettingsRoute
  '/system': typeof AppSystemRoute
  '/': typeof AppIndexRoute
  '/changes/$id': typeof AppChangesIdRoute
  '/jobs/$id': typeof AppJobsIdRoute
  '/runs/$id': typeof AppRunsIdRoute
  '/tasks/$id': typeof AppTasksIdRoute
  '/changes': typeof AppChangesIndexRoute
  '/tasks': typeof AppTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/signin': typeof SigninRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/system': typeof AppSystemRoute
  '/_app/': typeof AppIndexRoute
  '/_app/changes/$id': typeof AppChangesIdRoute
  '/_app/jobs/$id': typeof AppJobsIdRoute
  '/_app/runs/$id': typeof AppRunsIdRoute
  '/_app/tasks/$id': typeof AppTasksIdRoute
  '/_app/changes/': typeof AppChangesIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/settings'
    | '/system'
    | '/changes/$id'
    | '/jobs/$id'
    | '/runs/$id'
    | '/tasks/$id'
    | '/changes/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/settings'
    | '/system'
    | '/'
    | '/changes/$id'
    | '/jobs/$id'
    | '/runs/$id'
    | '/tasks/$id'
    | '/changes'
    | '/tasks'
  id:
    | '__root__'
    | '/_app'
    | '/signin'
    | '/_app/settings'
    | '/_app/system'
    | '/_app/'
    | '/_app/changes/$id'
    | '/_app/jobs/$id'
    | '/_app/runs/$id'
    | '/_app/tasks/$id'
    | '/_app/changes/'
    | '/_app/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system': {
      id: '/_app/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AppSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/changes/': {
      id: '/_app/changes/'
      path: '/changes'
      fullPath: '/changes/'
      preLoaderRoute: typeof AppChangesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/changes/$id': {
      id: '/_app/changes/$id'
      path: '/changes/$id'
      fullPath: '/changes/$id'
      preLoaderRoute: typeof AppChangesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/$id': {
      id: '/_app/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AppJobsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runs/$id': {
      id: '/_app/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof AppRunsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$id': {
      id: '/_app/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof AppTasksIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppSystemRoute: typeof AppSystemRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChangesIdRoute: typeof AppChangesIdRoute
  AppJobsIdRoute: typeof AppJobsIdRoute
  AppRunsIdRoute: typeof AppRunsIdRoute
  AppTasksIdRoute: typeof AppTasksIdRoute
  AppChangesIndexRoute: typeof AppChangesIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppSystemRoute: AppSystemRoute,
  AppIndexRoute: AppIndexRoute,
  AppChangesIdRoute: AppChangesIdRoute,
  AppJobsIdRoute: AppJobsIdRoute,
  AppRunsIdRoute: AppRunsIdRoute,
  AppTasksIdRoute: AppTasksIdRoute,
  AppChangesIndexRoute: AppChangesIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
